# Generated by Django 5.2.16 on 2026-07-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='N° de matrícula')),
                ('available_from', models.TimeField(verbose_name='Disponible desde')),
                ('available_to', models.TimeField(verbose_name='Disponible hasta')),
                ('specialties', models.ManyToManyField(related_name='doctors', to='specialties.specialty', verbose_name='Especialidades')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['name'],
            },
        ),
    ]
